version: '2'
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    ports:
    - '80:3000'
    links:
    - mysql
  mysql:
    container_name: mysql
    image: mysql/mysql-server
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=my_database
    - MYSQL_USER=nambi
    - MYSQL_PASSWORD=dev
    ports:
    - '3306:3306'
  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
    depends_on:
    - mysql
    ports:
    - '8080:80'
