version: '3'
services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_HOST: mysql
      MYSQL_DATABASE: horsemap
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
    - '3306:3306'

  app:
    container_name: docker-node-mysql
    build: .
    ports:
    - '80:3000'
    environment:
      DATABASE_HOST: mysql
      MYSQL_DATABASE: horsemap
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
    restart: on-failure

  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
    - mysql
    ports:
    - '8080:80'


