version: '3'
services:
  mysql:
    container_name: container_mysql
    image: mysql:5.7
    restart: always
    environment:
      DATABASE_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - ${MYSQL_EXT_PORT}:${MYSQL_INT_PORT}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    networks:
    - docker-net

  app:
    container_name: container_app
    build: .
    ports:
    - ${NODE_INT_PORT}:${NODE_EXT_PORT}
    environment:
      DATABASE_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    restart: on-failure
    networks:
    - docker-net
    volumes:
      - .:/usr/src/app

  phpmyadmin:
    container_name: container_myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
    - mysql
    ports:
    - ${PHPMYADMIN_EXT_PORT}:${PHPMYADMIN_INT_PORT}
    networks:
    - docker-net

networks:
  docker-net:
    driver: bridge
