-- MySQL Script generated by MySQL Workbench
-- Fri 23 Nov 2018 09:07:59 +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema horsemap
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `horsemap` ;

-- -----------------------------------------------------
-- Schema horsemap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horsemap` ;
USE `horsemap` ;

-- -----------------------------------------------------
-- Table `horsemap`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horsemap`.`user` ;

CREATE TABLE IF NOT EXISTS `horsemap`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(100) NULL,
  `lname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `mobile` VARCHAR(50) NULL,
  `landline` VARCHAR(50) NULL,
  `gender` TINYINT(5) NULL,
  `image` VARCHAR(255) NULL,
  `address_line1` VARCHAR(255) NULL,
  `address_line2` VARCHAR(255) NULL,
  `address_zip` VARCHAR(20) NULL,
  `address_state` VARCHAR(50) NULL,
  `address_country` VARCHAR(50) NULL,
  `address_city` VARCHAR(50) NULL,
  `user_type` TINYINT(5) NULL,
  `login_type` VARCHAR(10) NULL,
  `status` TINYINT(5) NULL,
  `created_at` TIMESTAMP(5) NULL,
  `updated_at` TIMESTAMP(5) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horsemap`.`user_advertisement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horsemap`.`user_advertisement` ;

CREATE TABLE IF NOT EXISTS `horsemap`.`user_advertisement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL,
  `price` VARCHAR(50) NULL,
  `level_id` VARCHAR(45) NULL,
  `gender` TINYINT(5) NULL,
  `age_id` VARCHAR(45) NULL,
  `colour_id` VARCHAR(45) NULL,
  `about` VARCHAR(50) NULL,
  `address_line1` VARCHAR(255) NULL,
  `address_line2` VARCHAR(255) NULL,
  `category_id` VARCHAR(45) NULL,
  `address_state` VARCHAR(255) NULL,
  `address_zip` VARCHAR(20) NULL,
  `address_city` VARCHAR(50) NULL,
  `address_country` VARCHAR(50) NULL,
  `status` TINYINT(5) NULL,
  `review_comments` VARCHAR(255) NULL,
  `created_at` TIMESTAMP(5) NULL,
  `updated_at` TIMESTAMP(5) NULL,
  `date` DATE NULL,
  `coordinates` DECIMAL NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_advertisement_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_advertisement_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `horsemap`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horsemap`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horsemap`.`media` ;

CREATE TABLE IF NOT EXISTS `horsemap`.`media` (
  `id` INT NOT NULL,
  `image` VARCHAR(255) NULL,
  `thumbnail` TINYINT(5) NULL,
  `order_no` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(5) NULL,
  `updated_at` TIMESTAMP(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horsemap`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horsemap`.`skills` ;

CREATE TABLE IF NOT EXISTS `horsemap`.`skills` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horsemap`.`user_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horsemap`.`user_skills` ;

CREATE TABLE IF NOT EXISTS `horsemap`.`user_skills` (
  `name` VARCHAR(100) NOT NULL,
  `user_advertisement_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  INDEX `fk_user_skills_user_advertisement1_idx` (`user_advertisement_id` ASC),
  INDEX `fk_user_skills_skills1_idx` (`skills_id` ASC),
  CONSTRAINT `fk_user_skills_user_advertisement1`
    FOREIGN KEY (`user_advertisement_id`)
    REFERENCES `horsemap`.`user_advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `horsemap`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horsemap`.`user_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horsemap`.`user_media` ;

CREATE TABLE IF NOT EXISTS `horsemap`.`user_media` (
  `name` VARCHAR(100) NOT NULL,
  `user_advertisement_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_user_media_user_advertisement1_idx` (`user_advertisement_id` ASC),
  INDEX `fk_user_media_media1_idx` (`media_id` ASC),
  CONSTRAINT `fk_user_media_user_advertisement1`
    FOREIGN KEY (`user_advertisement_id`)
    REFERENCES `horsemap`.`user_advertisement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_media_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `horsemap`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;